#!/bin/bash
# Install the agentvoice daemon.
#
# The bar widget arrives with `omarchy plugin add`, which clones this repo into
# ~/.config/omarchy/plugins/duaneoca.agentvoice/. That gets you the icon and
# the settings screen, but the thing that listens is a Python daemon with a
# few hundred megabytes of models behind it -- so it is a separate, explicit
# step, the way Omarchy installs Voxtype.
#
#   ./install.sh              interactive
#   ./install.sh --yes        no prompts, core engine only
#   ./install.sh --yes --oww  no prompts, both wake engines
#   ./install.sh --uninstall  take it all back off again
#   ./install.sh --dev        run from this checkout instead of a copy
#
# The daemon installs into ~/.local/share/agentvoice/app rather than running
# from the plugin directory, because `omarchy plugin remove` is an rm -rf and
# would otherwise delete the code a running service is executing -- and this
# script with it, leaving no way to finish the job.
set -euo pipefail

ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
DATA="${XDG_DATA_HOME:-$HOME/.local/share}/agentvoice"
VENV="$DATA/venv"
MODELS="$DATA/models"
APP="$DATA/app"
BINDIR="$HOME/.local/bin"
UNITDIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
PYTHON_VERSION=3.13

# True when this script is the installed copy rather than a checkout or the
# plugin directory -- which changes what it is safe to delete. Both sides are
# resolved because either can be a symlink.
SELF_IS_APP=0
[[ "$(readlink -f "$ROOT")" == "$(readlink -f "$APP")" ]] && SELF_IS_APP=1

ASSUME_YES=0
WANT_OWW=""
UNINSTALL=0
DEV=0
for arg in "$@"; do
  case "$arg" in
    --yes|-y) ASSUME_YES=1 ;;
    --uninstall|--remove) UNINSTALL=1 ;;
    --dev) DEV=1 ;;
    --oww|--openwakeword) WANT_OWW=1 ;;
    --no-oww) WANT_OWW=0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

have() { command -v "$1" >/dev/null 2>&1; }

# Checked up front rather than discovered at the download step, with the
# environment already built and the models missing. Not for an uninstall:
# removal downloads nothing, and refusing to run because a tool the *install*
# needs has since been removed strands the user with something they cannot
# take off. CI found that one -- its runners have no bsdtar.
if [[ $UNINSTALL == 0 ]]; then
  missing=""
  for tool in curl bsdtar jq; do have "$tool" || missing="$missing $tool"; done
  if [[ -n ${missing// } ]]; then
    echo "  missing required tools:$missing" >&2
    echo "  install them with: omarchy pkg add$missing" >&2
    exit 1
  fi
fi
say()  { if have gum; then gum style --foreground 4 "  $*"; else echo "  $*"; fi; }
ok()   { if have gum; then gum style --foreground 2 "  $*"; else echo "  $*"; fi; }
warn() { if have gum; then gum style --foreground 3 "  $*"; else echo "  $*" >&2; fi; }

ask() {
  local prompt="$1"
  (( ASSUME_YES )) && return 1
  if have gum && [[ -t 0 ]]; then gum confirm "$prompt"; else
    read -r -p "  $prompt [y/N] " a; [[ ${a,,} == y* ]]
  fi
}

# --- taking it off again ---------------------------------------------------
# Written because there was no way to. Something that installs a daemon, a
# systemd unit, two commands on PATH and the better part of a gigabyte should
# be able to remove them, and a project that cannot be uninstalled is a bad
# guest on somebody's machine.
#
# What it deliberately does not touch: your voice. The trained verifiers and
# the clips they were built from are twenty-five recordings each and cannot be
# regenerated by any amount of downloading. Nor the keyring, which holds API
# keys this never created. Both are named on the way out so the choice is
# yours rather than ours.
if [[ $UNINSTALL == 1 ]]; then
  echo
  if ! (( ASSUME_YES )) && ! ask "Remove the agentvoice engine, service and commands?"; then
    echo "  Left alone."
    # Non-zero on purpose. The widget's Remove button chains this with
    # `&& omarchy plugin remove`, so exiting 0 here would decline the engine
    # and delete the user interface anyway -- the opposite of the answer.
    exit 1
  fi
  say "Removing agentvoice."

  if systemctl --user list-unit-files agentvoice.service &>/dev/null; then
    systemctl --user disable --now agentvoice.service 2>/dev/null || true
  fi
  rm -f "$UNITDIR/agentvoice.service"
  systemctl --user daemon-reload 2>/dev/null || true
  ok "Stopped and removed the user service"

  for cmd in agentvoice agentvoice-train-verifier; do
    rm -f "$BINDIR/$cmd"
  done
  ok "Removed the commands from $BINDIR"

  rm -rf "$VENV" "$MODELS"
  ok "Removed the environment and the models"

  # Last, because this script is usually running from inside it. That is
  # safe: bash holds the script's fd open, so the unlinked inode lives
  # until the last line runs. Measured, not assumed -- tests/test_uninstall.py
  # runs the installed copy and checks it reaches the end.
  if [[ -L $APP ]]; then rm -f "$APP"; else rm -rf "$APP"; fi
  ok "Removed the installed daemon"

  rm -rf "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/agentvoice"

  # Existing and holding something are different questions, and the first one
  # is the wrong one: install.sh creates these directories itself, so asking
  # `-d` meant promising to have kept twenty-five recordings that were never
  # made, and leaving two empty directories and a parent behind to prove it.
  KEPT=""
  for d in verifiers verifier-training wakewords; do
    [[ -d "$DATA/$d" ]] || continue
    if [[ -n "$(ls -A "$DATA/$d" 2>/dev/null)" ]]; then
      KEPT="$KEPT\n    $DATA/$d"
    else
      rmdir "$DATA/$d" 2>/dev/null || true
    fi
  done
  # rmdir, not rm -rf: it goes only if something above was genuinely kept.
  rmdir "$DATA" 2>/dev/null || true

  # The key file fallback, for machines with no keyring. The keyring gets
  # named on the way out and this did not, so a key left here survived
  # unmentioned -- and when there was none, an empty directory survived
  # instead. Same question as above, asked of the other parent.
  CFGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/agentvoice"
  KEPT_KEY=""
  if [[ -d $CFGDIR ]]; then
    if [[ -n "$(ls -A "$CFGDIR" 2>/dev/null)" ]]; then
      KEPT_KEY="$CFGDIR"
    else
      rmdir "$CFGDIR" 2>/dev/null || true
    fi
  fi

  echo
  ok "Done."
  cat <<NEXT

  The bar widget is Omarchy's to remove:
    omarchy plugin remove duaneoca.agentvoice

  Left alone on purpose, because this did not create them and you may
  want them again:
NEXT
  [[ -n $KEPT ]] && printf "  Your voice — recordings and trained verifiers:%b\n\n" "$KEPT"
  [[ -n $KEPT_KEY ]] && printf "  An API key you put in a file:\n    %s\n\n" "$KEPT_KEY"
  cat <<NEXT
  API keys in the login keyring:
    secret-tool search --all service agentvoice
    secret-tool clear service agentvoice endpoint <host>

  Whisper's model cache, shared with anything else using it:
    ~/.cache/huggingface        ($(du -sh ~/.cache/huggingface 2>/dev/null | cut -f1 || echo "not present"))

  Settings in ~/.config/omarchy/shell.json, and any keybinds you added
  to ~/.config/hypr/bindings.lua.
NEXT
  exit 0
fi

# --- uv, the only thing we need from the system ---------------------------
if ! have uv; then
  say "Installing uv (the official 'extra' repo package)…"
  if have omarchy-pkg-add; then omarchy-pkg-add uv
  elif [[ -t 0 ]]; then sudo pacman -S --needed --noconfirm uv
  else pkexec pacman -S --needed --noconfirm uv; fi
fi

# --- interpreter and wheels -----------------------------------------------
# Deliberately a uv-managed CPython rather than /usr/bin/python: Arch is
# rolling, and a venv built against the system interpreter stops importing the
# next time Arch bumps it.
say "Creating the environment (CPython $PYTHON_VERSION, managed by uv)…"
mkdir -p "$DATA" "$MODELS" "$DATA/verifiers" "$DATA/wakewords"
[[ -d $VENV ]] || uv venv --python "$PYTHON_VERSION" "$VENV" >/dev/null

say "Installing dependencies…"
VIRTUAL_ENV="$VENV" uv pip install --quiet -r "$ROOT/requirements.txt"

# Settings decide before the prompt does: if the wake engine is already set
# to openWakeWord, installing without it produces a daemon that cannot start
# the engine it is configured for.
if [[ -z $WANT_OWW ]] && have jq; then
  if [[ "$(jq -r '[.bar.layout[]?[]? | select(.id=="duaneoca.agentvoice")][0].engine // empty' \
        "${XDG_CONFIG_HOME:-$HOME/.config}/omarchy/shell.json" 2>/dev/null)" == "openwakeword" ]]; then
    say "Settings already use openWakeWord; installing it."
    WANT_OWW=1
  fi
fi

if [[ -z $WANT_OWW ]] && (( ASSUME_YES )); then
  # --yes means yes. It used to reach ask(), which declines under --yes, so
  # the unattended install quietly skipped the engine with real rejection.
  WANT_OWW=1
fi

if [[ -z $WANT_OWW ]]; then
  echo
  cat <<'WHY'
  A second wake-word engine is available. Vosk takes any phrase but scores
  phonetic neighbours as high as the real one -- measured here, "hey cloud"
  scores 1.00 against a "hey claude" grammar, which is how a podcast wakes it.
  openWakeWord has four fixed phrases and real rejection, and can be trained
  on your own voice afterwards. It costs about 154MB.

WHY
  if ask "Install openWakeWord as well?"; then WANT_OWW=1; else WANT_OWW=0; fi
fi

if [[ $WANT_OWW == 1 ]]; then
  say "Installing openWakeWord…"
  VIRTUAL_ENV="$VENV" uv pip install --quiet -r "$ROOT/requirements-openwakeword.txt"
fi

# --- models ----------------------------------------------------------------
fetch_vosk() {
  local dir="$MODELS/vosk-model-small-en-us-0.15"
  [[ -d $dir ]] && return 0
  say "Downloading the Vosk model (40MB)…"
  curl -fL --progress-bar -o "$MODELS/.vosk.zip" \
    https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip
  bsdtar -xf "$MODELS/.vosk.zip" -C "$MODELS" && rm -f "$MODELS/.vosk.zip"
}

fetch_voice() {
  local name="$1" quality="$2"
  local dir="$MODELS/piper" file="en_US-$1-$2.onnx"
  mkdir -p "$dir"
  [[ -f "$dir/$file" ]] && return 0
  local base="https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/$1/$2"
  say "Downloading the voice $file (60MB)…"
  curl -fL --progress-bar -o "$dir/$file"      "$base/$file"
  curl -fL --progress-bar -o "$dir/$file.json" "$base/$file.json"
}

# What the settings already ask for. An uninstall leaves shell.json alone,
# so a reinstall that fetched only the default would leave the voice set to
# something that is not there -- which degrades to silence with the reason in
# a log nobody reads.
configured() {
  local key="$1"
  local file="${XDG_CONFIG_HOME:-$HOME/.config}/omarchy/shell.json"
  have jq || return 0
  # Both guards matter under `set -e`. jq exits 2 on a file that is not there,
  # and this runs inside a command substitution being assigned, so that 2 left
  # the whole installer dead -- after 700MB of downloads, with nothing printed.
  # A machine with no shell.json is not an error: it is every machine where the
  # widget has not been configured yet, which is most of them on a first run.
  # Neither of the two machines this was written on could reproduce it.
  [[ -f $file ]] || return 0
  jq -r --arg k "$key" \
    '[.bar.layout[]?[]? | select(.id=="duaneoca.agentvoice")][0][$k] // empty' \
    "$file" 2>/dev/null || true
}

fetch_vosk
fetch_voice lessac medium

WANT_VOICE="$(configured voice)"
if [[ -n ${WANT_VOICE:-} && $WANT_VOICE != lessac-medium ]]; then
  say "Settings ask for the voice $WANT_VOICE; fetching it too."
  fetch_voice "${WANT_VOICE%-*}" "${WANT_VOICE##*-}"
fi

# --- the daemon itself -----------------------------------------------------
# Copied out of the plugin directory so removing the bar widget cannot delete
# a running service, and so the uninstaller survives to be run. In a checkout
# --dev links instead, because editing a copy and restarting the original is
# a bad afternoon.
# When $APP *is* where this script lives, `rm -rf "$APP"` deletes the source it
# is about to copy from; the cp then fails and set -e leaves an empty app/ and
# a broken install. That is reachable: the widget's Remove button runs
# $APP/install.sh, and a mis-passed flag once turned that into an install.
if (( SELF_IS_APP )); then
  ok "The daemon in $APP is already the one being installed"
elif [[ $DEV == 1 ]]; then
  rm -rf "$APP"
  ln -s "$ROOT" "$APP"
  ok "Linked $APP -> $ROOT (development)"
else
  rm -rf "$APP"
  mkdir -p "$APP"
  cp -r "$ROOT/daemon" "$ROOT/bin" "$ROOT/desktop" "$APP/"
  cp "$ROOT/install.sh" "$ROOT/requirements.txt" \
     "$ROOT/requirements-openwakeword.txt" "$APP/"
  ok "Installed the daemon into $APP"
fi

# --- commands on PATH ------------------------------------------------------
mkdir -p "$BINDIR"
for cmd in agentvoice agentvoice-train-verifier; do
  ln -sf "$APP/bin/$cmd" "$BINDIR/$cmd"
done
ok "Installed agentvoice and agentvoice-train-verifier into $BINDIR"

# --- service ---------------------------------------------------------------
# Written rather than copied, so the unit carries this checkout's real path.
mkdir -p "$UNITDIR"
sed -e "s|@ROOT@|$APP|g" -e "s|@VENV@|$VENV|g" \
    "$ROOT/desktop/agentvoice.service.in" > "$UNITDIR/agentvoice.service"
# Unguarded, this was the last line of a successful install and could undo it:
# `set -e` turned a machine with no systemd user session -- a container, an ssh
# login without one, a distribution that is not using systemd -- into an exit
# after every file was already in place, with the failure attributed to
# nothing. The uninstall path has always tolerated this; the install path did
# not. Say what happened and carry on, because everything needed to start it by
# hand is installed by this point.
if ! systemctl --user daemon-reload 2>/dev/null; then
  warn "No systemd user session here, so the service was not registered."
  warn "The unit is at $UNITDIR/agentvoice.service; run 'agentvoice start' to"
  warn "run the daemon in the foreground instead."
fi
ok "Installed the user service"

echo
ok "Done."
cat <<NEXT

  Add the bar widget, if you have not already:
    omarchy plugin add https://github.com/duaneoca/agent-voice.git --enable

  Start listening:
    agentvoice start

  The Whisper model downloads on first use (~75MB).

  Optional keybinds -- paste into ~/.config/hypr/bindings.lua. They are not
  installed for you, because that file is yours:

    o.bind("F8", "Talk to the agent (push-to-talk)", "agentvoice talk")
    o.bind("F8", "End the turn (push-to-talk)", "agentvoice talk-end", { release = true })
    o.bind("SUPER + CTRL + SPACE", "Stop the agent talking", "agentvoice interrupt")
    o.bind("SUPER + ALT + SPACE", "Release or re-engage the mic", "agentvoice mic")
NEXT
