#!/usr/bin/env bash
# Regenerate models.lock: the revision every Piper voice is fetched from, and
# a sha256 for each file an install downloads.
#
#   ./bench/pin-models.sh > models.lock
#
# Cheap on purpose. The .onnx hashes come out of Hugging Face's own LFS
# metadata, which is already a sha256 of the file, so refreshing seven voices
# costs one API call rather than half a gigabyte of downloads. The .json files
# are plain git blobs -- their metadata carries a git SHA-1, not a content
# hash -- so those are fetched and hashed, a few kilobytes each.
#
# The Vosk archive is 40MB and is hashed by downloading it, so it is only
# refreshed when --vosk is passed.
set -euo pipefail

REPO=rhasspy/piper-voices
VOSK_URL=https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip

# Every voice the settings page offers, plus the ones the verifier trainer
# fetches to contrast against. A voice absent from the lock is not installed,
# so this list is the list.
VOICES=(lessac-medium lessac-low amy-medium ryan-medium joe-medium
        kristin-medium hfc_male-medium)

WANT_VOSK=0
[[ ${1:-} == --vosk ]] && WANT_VOSK=1

note() { printf '%s\n' "$*" >&2; }

REV="$(curl -sfL "https://huggingface.co/api/models/$REPO" \
       | python3 -c 'import json,sys; print(json.load(sys.stdin)["sha"])')"
[[ -n $REV ]] || { note "could not read the repository revision"; exit 1; }
note "revision $REV"

cat <<HEADER
# Pinned model downloads: a revision to fetch from, and a hash to check what
# arrived against. Generated by bench/pin-models.sh -- edit that, not this.
#
# Why pin at all. Both of these came from a mutable location --
# huggingface.co/.../resolve/main is a branch, not a version -- with nothing
# checking what came back. So an install was not reproducible (the file could
# change underneath you between two installs of the same commit), and nothing
# would notice if it changed for a worse reason than an upstream edit. https
# and refusing redirects covers the wire; this covers the far end.
#
# A voice with no entry here is not installed, deliberately: the point is that
# nothing arrives unverified. The list is every voice the settings page offers
# plus the ones the verifier trainer fetches for contrast.
#
# To refresh:  ./bench/pin-models.sh [--vosk] > models.lock

# The piper-voices revision every voice below is fetched from.
revision piper $REV

HEADER

# One request for every .onnx, answered from LFS metadata.
paths=()
for v in "${VOICES[@]}"; do
  n="${v%-*}"; q="${v##*-}"
  paths+=("en/en_US/$n/$q/en_US-$n-$q.onnx")
done
python3 - "$REPO" "$REV" "${paths[@]}" <<'PY'
import json, subprocess, sys
repo, rev, *paths = sys.argv[1:]
body = json.dumps({"paths": paths})
out = subprocess.run(
    ["curl", "-sfL", "-X", "POST", "-H", "Content-Type: application/json",
     "-d", body, f"https://huggingface.co/api/models/{repo}/paths-info/{rev}"],
    capture_output=True, text=True, timeout=180, check=True)
found = {}
for entry in json.loads(out.stdout):
    oid = (entry.get("lfs") or {}).get("oid")
    if not oid:
        sys.exit(f"{entry['path']} is not an LFS file, so its metadata "
                 f"carries no content hash -- fetch and hash it instead")
    found[entry["path"]] = oid
missing = [p for p in paths if p not in found]
if missing:
    sys.exit("not found at this revision: " + ", ".join(missing))
for p in paths:
    print(f"sha256 {p.rsplit('/', 1)[1]:<34} {found[p]}")
PY

# The .json files are small, so they are fetched and hashed.
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
for v in "${VOICES[@]}"; do
  n="${v%-*}"; q="${v##*-}"; f="en_US-$n-$q.onnx.json"
  curl -sfL --proto '=https' -o "$tmp/$f" \
    "https://huggingface.co/$REPO/resolve/$REV/en/en_US/$n/$q/$f"
  printf 'sha256 %-34s %s\n' "$f" "$(sha256sum "$tmp/$f" | cut -d' ' -f1)"
done

echo
echo "# Vosk publishes versioned URLs rather than a branch, so this is a hash"
echo "# of what that URL served rather than a pin against drift."
if (( WANT_VOSK )); then
  note "downloading the Vosk model to hash it (40MB)"
  curl -sfL --proto '=https' -o "$tmp/vosk.zip" "$VOSK_URL"
  printf 'sha256 %-34s %s\n' "${VOSK_URL##*/}" \
    "$(sha256sum "$tmp/vosk.zip" | cut -d' ' -f1)"
else
  note "keeping the existing Vosk hash; pass --vosk to re-download it"
  grep '^sha256 vosk-' "$(dirname "$(readlink -f "$0")")/../models.lock"
fi
